Repository Henriknn01/ShopBackend, pull requests merged in 2023-05, with the labels that each got.

#36 Filtering
  ShopBackend/settings.py
  ShopCMS/djoserSerializers.py
  ShopCMS/models.py
  ShopCMS/serializers.py
  ShopCMS/views.py
Labels: development

#38 Filtering
  ShopCMS/admin.py
  ShopCMS/serializers.py
  ShopCMS/urls.py
  ShopCMS/views.py
Labels: development

#39 Feature category images
  ShopCMS/models.py
  ShopCMS/serializers.py
  ShopCMS/views.py
Labels: development

#42 added 1.21.5 version of swagger
  requirements.txt
Labels: development

#43 added rest swagger
  requirements.txt
Labels: development

#44 added critical pip install, and added image serilizer
  ShopCMS/serializers.py
  requirements.txt
Labels: development

#45 Order details update
  ShopBackend/settings.py
  ShopCMS/admin.py
  ShopCMS/models.py
  ShopCMS/serializers.py
  ShopCMS/urls.py
  ShopCMS/views.py
Labels: development

#46 changed src to alt,
  ShopCMS/models.py
  ShopCMS/views.py
Labels: development

#47 added firstname, lastname and newsletter
  ShopCMS/serializers.py
Labels: development

#48 removed email conformation for new users
  ShopBackend/settings.py
Labels: development

#50 changed representation of models, so we can post ids
  ShopCMS/serializers.py
Labels: development

#51 changed perm
  Dockerfile
  ShopCMS/serializers.py
Labels: development

#52 display ahtor first name on reviews
  ShopCMS/serializers.py
Labels: development

#53 Docker django
  Dockerfile
  ShopBackend/settings.py
  ShopCMS/serializers.py
  dokcer-compose.yml
Labels: development

#55 added static root
  ShopBackend/settings.py
Labels: development

#56 changed static to staticfiles
  ShopBackend/settings.py
  ShopBackend/urls.py
Labels: development

#57 added csrf setting
  ShopBackend/settings.py
Labels: bug

#59 removed collect static
  Dockerfile
Labels: development

#60 added makemigrations
  Dockerfile
Labels: development

#63 added swagger url location
  ShopBackend/settings.py
Labels: development

#66 added banner image to blog
  ShopCMS/serializers.py
Labels: development

#70 Update models.py
  ShopCMS/models.py
Labels: bug, development

#73 Readme and license
  README.md
  documentation/README.md
  documentation/Wave_Environment.postman_environment.json
  documentation/Wave_Shop_Tests.postman_collection.json
Labels: documentation

#75 moved sprint report
  documentation/SprintReport-Backend
Labels: documentation

#76 added links and test user
  README.md
Labels: documentation

#77 replaced admin_username to admin_email to make it easier to understand
  documentation/README.md
Labels: documentation
